### ISSUE TITLE
Does anyone knows how many read/writes can I do in aiven free postgress DB per month? Any Rough number?

### ISSUE THREAD

**Issue by NikhilKalloli** [aiven/aiven-docs#569]
### Description

Does anyone knows how many read/writes can I do in aiven free postgress DB per month? Any Rough number?

**Comment by wojcik-dorota** [comment]
Thanks for reaching out, @NikhilKalloli ! Please see the answer on the [community forum](https://aiven.io/community/forum/t/how-many-read-writes-can-i-do-in-aiven-free-postgress-db-per-month/1472).
